/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import javax.swing.JOptionPane;

/**
 *
 * @author ANGIE GOMEZ
 */
public class frmComida extends javax.swing.JFrame {

    /**
     * Creates new form frmComida
     */
    public frmComida() {
        initComponents();
        listar();
    }
    
    public void listar(){
        pkgNegocio.clsDAOComida obj;
        obj=new pkgNegocio.clsDAOComida();
        tbl_Catalogo.setModel(obj.listar(tbl_Catalogo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bar = new javax.swing.JToolBar();
        btnAgregarComida = new javax.swing.JButton();
        btnConsultarComida = new javax.swing.JButton();
        btnBorrarComida = new javax.swing.JButton();
        btnModificarComida = new javax.swing.JButton();
        btnCerrarComida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Catalogo = new javax.swing.JTable();
        lblMensaje = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bar.setRollover(true);

        btnAgregarComida.setText("Agregar");
        btnAgregarComida.setToolTipText("Agrega y lista personas");
        btnAgregarComida.setFocusable(false);
        btnAgregarComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarComida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComidaActionPerformed(evt);
            }
        });
        bar.add(btnAgregarComida);

        btnConsultarComida.setText("Consultar");
        btnConsultarComida.setFocusable(false);
        btnConsultarComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarComida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarComidaActionPerformed(evt);
            }
        });
        bar.add(btnConsultarComida);

        btnBorrarComida.setText("Borrar");
        btnBorrarComida.setFocusable(false);
        btnBorrarComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarComida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBorrarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarComidaActionPerformed(evt);
            }
        });
        bar.add(btnBorrarComida);

        btnModificarComida.setText("Modificar");
        btnModificarComida.setFocusable(false);
        btnModificarComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarComida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarComidaActionPerformed(evt);
            }
        });
        bar.add(btnModificarComida);

        btnCerrarComida.setText("Cerrar");
        btnCerrarComida.setFocusable(false);
        btnCerrarComida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarComida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarComidaActionPerformed(evt);
            }
        });
        bar.add(btnCerrarComida);

        jLabel1.setText("Código");

        jLabel2.setText("Nombre Producto");

        jLabel3.setText("Precio");

        tbl_Catalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE PRODUCTO", "PRECIO"
            }
        ));
        jScrollPane2.setViewportView(tbl_Catalogo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMensaje)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComidaActionPerformed
        // TODO add your handling code here:
        pkgNegocio.clsDAOComida obj;
        obj=new pkgNegocio.clsDAOComida();
        obj.setCodigo(txtCodigo.getText());
        obj.setNombre_producto(txtNombreProducto.getText());
        obj.setPrecio(txtPrecio.getText());

        if (obj.insertarComida() == false){
            JOptionPane.showMessageDialog(rootPane, "Se insertó");
            //lblMensaje.setText("Se insertó");
            listar();
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No se insertó");
        }
        txtCodigo.setText("");
        txtNombreProducto.setText("");
        txtPrecio.setText("");
        
    }//GEN-LAST:event_btnAgregarComidaActionPerformed

    private void btnConsultarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarComidaActionPerformed
        // TODO add your handling code here:
        pkgNegocio.clsDAOComida obj;
        obj=new pkgNegocio.clsDAOComida();
        obj.setCodigo(txtCodigo.getText());

        String resultado=obj.consultarComida(2);
        String resultado2=obj.consultarComida(3);
        if(resultado.equals("no")){
            JOptionPane.showMessageDialog(rootPane, "No esta");
        }
        else{
            txtNombreProducto.setText(resultado);
            txtPrecio.setText(resultado2);
        }
    }//GEN-LAST:event_btnConsultarComidaActionPerformed

    private void btnBorrarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarComidaActionPerformed
        // TODO add your handling code here:
        pkgNegocio.clsDAOComida obj;
        obj=new pkgNegocio.clsDAOComida();

        int fila=tbl_Catalogo.getSelectedRow();
        if (fila != -1){
            String codigo=tbl_Catalogo.getValueAt(fila, 0).toString();
            obj.setCodigo(codigo);
            obj.borrarComida();
            JOptionPane.showMessageDialog(rootPane, "Se eliminó fila");
            listar();
            
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Para eliminar deberá seleccionar una fila!!!!");
        }
    }//GEN-LAST:event_btnBorrarComidaActionPerformed

    private void btnModificarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarComidaActionPerformed
        // TODO add your handling code here:
        pkgNegocio.clsDAOComida obj;
        obj=new pkgNegocio.clsDAOComida();
        obj.setCodigo(txtCodigo.getText());
        obj.setNombre_producto(txtNombreProducto.getText());
        obj.setPrecio(txtPrecio.getText());

        if(obj.modificarComida() == false){
            listar();
            JOptionPane.showMessageDialog(rootPane, "Se modificó");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No Se modificó");
        }
    }//GEN-LAST:event_btnModificarComidaActionPerformed

    private void btnCerrarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarComidaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmComida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar bar;
    private javax.swing.JButton btnAgregarComida;
    private javax.swing.JButton btnBorrarComida;
    private javax.swing.JButton btnCerrarComida;
    private javax.swing.JButton btnConsultarComida;
    private javax.swing.JButton btnModificarComida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tbl_Catalogo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
